version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5440
    ports:
      # Expose weird port on host to avoid collisions
      - 5440:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always

  app:
    image: node:16
    command: sh -c "yarn install && PORT=5003 yarn dev"
    volumes:
      - ./components:/app/components
      - ./db:/app/db
      - ./next-env.d.ts:/app/next-env.d.ts
      - ./package.json:/app/package.json
      - ./pages:/app/pages
      - ./tsconfig.json:/app/tsconfig.json
      - ./types:/app/types
      - ./utils:/app/utils
      - ./yarn.lock:/app/yarn.lock
      - cache:/usr/local/share/.cache/yarn/v6
      - node_modules:/app/node_modules
    ports:
      # Weird port to avoid collisions
      - 5003:5003
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/postgres
    working_dir: /app
    restart: always

volumes:
  dbdata:
  node_modules:
  cache: